---

- name: Set Filebeat version if defined
  set_fact:
    fb_package_name: '{{ fb_package_name }}={{ filebeat_version }}'
  when: filebeat_version.find('.x') == -1

- block:
    - name: Install dependency for Debian
      package:
        name: apt-transport-https
        state: present
      register: debian_dependency
      until: debian_dependency is succeeded

    - import_tasks: Debian-apt-repository.yml 

    - name: Install filebeat
      apt:
        name: '{{ fb_package_name }}'
        state: present
        update_cache: yes
      register: installed_package
      until: installed_package is succeeded
      notify: '{{ fb_service_handlers }}'

    - name: Create folder path for service script
      file:
        path: /usr/lib/systemd/system
        state: directory
  
  become: true
